apiVersion: v1
kind: Service
metadata:
  name: patientsearchserviceapi-service
spec:
  selector:
    app: patientsearchserviceapi-pod
  ports:
  - port: 30029
    name: grpc
    nodePort: 30029
    targetPort: 30029
  - port: 30039
    name: http
    nodePort: 30039
    targetPort: 30039
  type: LoadBalancer
